# Generated by Django 3.2.5 on 2021-07-31 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان سوال')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام دانش آموز')),
            ],
            options={
                'verbose_name': 'دانش آموز',
                'verbose_name_plural': 'دانش آموزان',
            },
        ),
        migrations.CreateModel(
            name='StudentsAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.students')),
            ],
            options={
                'verbose_name': 'جواب دانش آموز',
                'verbose_name_plural': 'جواب های دانش آموزان',
            },
        ),
        migrations.CreateModel(
            name='QuestionsAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.CharField(max_length=300, verbose_name='جواب صحیح')),
                ('first_option', models.CharField(max_length=300, verbose_name='گزینه اول')),
                ('second_option', models.CharField(max_length=300, verbose_name='گزینه دوم')),
                ('third_option', models.CharField(max_length=300, verbose_name='گزینه سوم')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.questions')),
            ],
            options={
                'verbose_name': 'جواب سوالات',
                'verbose_name_plural': ' جواب های سوالات',
            },
        ),
    ]
