# Generated by Django 3.2.5 on 2021-07-31 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_questions_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.categories'),
        ),
    ]
