# Generated by Django 3.2.5 on 2021-08-01 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_questions_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsanswers',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.questions'),
        ),
    ]
