# Generated by Django 3.2.5 on 2021-08-01 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_questionsanswers_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='category',
        ),
    ]
