# Generated by Django 3.2.5 on 2021-08-01 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_remove_questions_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quiz.categories'),
            preserve_default=False,
        ),
    ]
