# Generated by Django 3.2.5 on 2021-08-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_questions_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='نام دانش آموز'),
        ),
    ]
