# Generated by Django 3.2.5 on 2021-08-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20210802_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionsanswers',
            name='correct_answer',
        ),
        migrations.RemoveField(
            model_name='questionsanswers',
            name='first_option',
        ),
        migrations.RemoveField(
            model_name='questionsanswers',
            name='second_option',
        ),
        migrations.RemoveField(
            model_name='questionsanswers',
            name='third_option',
        ),
        migrations.AddField(
            model_name='questionsanswers',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questionsanswers',
            name='option',
            field=models.CharField(default=False, max_length=300, verbose_name='گزینه'),
            preserve_default=False,
        ),
    ]
