# Generated by Django 3.2.5 on 2021-08-02 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20210802_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionsanswers',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='گزینه صحیح'),
        ),
        migrations.AlterField(
            model_name='questionsanswers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.questions'),
        ),
    ]
