# Generated by Django 3.2.5 on 2021-08-02 13:10

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_auto_20210802_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsanswers',
            name='answer_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), default=[1], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentsanswers',
            name='questions_id',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), default=[1], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionsanswers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qanswer', to='quiz.questions'),
        ),
    ]
