# Generated by Django 3.2.6 on 2021-08-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=250, null=True, verbose_name='عنوان سوال'),
        ),
    ]
