# Generated by Django 3.2.6 on 2021-08-07 11:31

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_students_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_id', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), size=None, verbose_name='شماره سوال')),
                ('answer_id', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None), blank=True, null=True, size=None, verbose_name='شماره جواب')),
                ('correct_percentage', models.IntegerField(blank=True, default=0, null=True, verbose_name='درصد صحیح جواب')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.students', verbose_name='نام دانش آموز')),
            ],
        ),
    ]
