# Generated by Django 3.2.6 on 2021-08-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_studentanswers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswers',
            name='correct_percentage',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='درصد صحیح جواب'),
        ),
    ]
