# Generated by Django 3.2.7 on 2021-09-17 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='T1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='T2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Throgh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=100)),
                ('toT1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.t1')),
                ('toT2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.t2')),
            ],
        ),
        migrations.AddField(
            model_name='t2',
            name='m2m',
            field=models.ManyToManyField(limit_choices_to=2, through='app.Throgh', to='app.T1'),
        ),
    ]
